// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnkaoqwebsuztxtftpfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZua2FvcXdlYnN1enR4dGZ0cGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5NTU4NTgsImV4cCI6MjA1MTUzMTg1OH0.uOvsqa22uybnHa4X1oXL2RgBntaKi3JycTCbgZUcNg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);